"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import {
    QrCode,
    User,
    Send,
    ShieldCheck,
    MapPin,
    Calendar,
    AlertCircle,
    CheckCircle2,
    RefreshCcw,
    Info
} from "lucide-react"
import { toast } from "sonner"

export default function CheckinTester() {
    const [token, setToken] = useState("")
    const [userId, setUserId] = useState("admin")
    const [loading, setLoading] = useState(false)
    const [result, setResult] = useState<any>(null)
    const [error, setError] = useState<string | null>(null)

    const API_URL = process.env.NEXT_PUBLIC_API_URL || ''

    const handleScan = async () => {
        if (!token || !userId) {
            toast.error("Please provide both token and userId")
            return
        }

        setLoading(true)
        setError(null)
        setResult(null)

        try {
            const res = await fetch(`${API_URL}/api/qrcode/scan`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ token, userId })
            })

            const data = await res.json()

            if (!res.ok) {
                throw new Error(data.error || 'Failed to process scan')
            }

            setResult(data)
            toast.success("Check-in successful!")
        } catch (err: any) {
            setError(err.message)
            toast.error(err.message)
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="min-h-screen flex items-center justify-center bg-zinc-950 text-white p-4 font-sans selection:bg-orange-500/30">
            {/* Dynamic Background */}
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,0.1),transparent_50%)] pointer-events-none" />
            <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-10 pointer-events-none" />

            <Card className="w-full max-w-2xl bg-zinc-900/80 backdrop-blur-xl border-zinc-800 shadow-[0_32px_64px_-12px_rgba(0,0,0,0.8)] relative z-10 overflow-hidden">
                {/* Animated Accent Bar */}
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-orange-500 via-amber-500 to-orange-600 animate-pulse" />

                <CardHeader className="space-y-1 pt-8 pb-6">
                    <div className="flex items-center gap-3 text-orange-400 mb-2">
                        <div className="p-2 bg-orange-500/10 rounded-lg">
                            <QrCode className="w-5 h-5" />
                        </div>
                        <span className="text-xs font-black uppercase tracking-[0.2em]">Check-in Simulator</span>
                    </div>
                    <CardTitle className="text-4xl font-black tracking-tighter italic lg:text-5xl">
                        QR TEST <span className="text-orange-500 text-stroke-sm">DEVICE</span>
                    </CardTitle>
                    <CardDescription className="text-zinc-400 text-base max-w-md">
                        Simulate a mobile scan event using a dynamic QR token generated by the booth machine.
                    </CardDescription>
                </CardHeader>

                <CardContent className="space-y-8 pb-10">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* User Identification */}
                        <div className="space-y-3">
                            <label className="text-xs font-bold text-zinc-500 uppercase flex items-center gap-2">
                                <User className="w-3 h-3" />
                                User Identifier
                            </label>
                            <Input
                                placeholder="Username or ID"
                                value={userId}
                                onChange={(e) => setUserId(e.target.value)}
                                className="bg-zinc-950/50 border-zinc-800 h-12 text-white focus:ring-orange-500 focus:border-orange-500 rounded-xl transition-all"
                            />
                        </div>

                        {/* Token Input */}
                        <div className="space-y-3">
                            <label className="text-xs font-bold text-zinc-500 uppercase flex items-center gap-2">
                                <ShieldCheck className="w-3 h-3" />
                                Dynamic Token
                            </label>
                            <Input
                                placeholder="e.g. 73d156d22..."
                                value={token}
                                onChange={(e) => setToken(e.target.value)}
                                className="bg-zinc-950/50 border-zinc-800 h-12 font-mono text-sm text-orange-400 focus:ring-orange-500 focus:border-orange-500 rounded-xl transition-all"
                            />
                        </div>
                    </div>

                    <Button
                        onClick={handleScan}
                        disabled={loading || !token || !userId}
                        className="w-full bg-orange-600 hover:bg-orange-500 text-white font-black h-14 rounded-2xl shadow-xl shadow-orange-950/20 group transition-all duration-300 transform active:scale-[0.98]"
                    >
                        {loading ? (
                            <RefreshCcw className="w-6 h-6 animate-spin" />
                        ) : (
                            <div className="flex items-center gap-3">
                                SCAN & CHECK-IN
                                <Send className="w-5 h-5 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" />
                            </div>
                        )}
                    </Button>

                    {/* Results Section */}
                    {(result || error) && (
                        <div className={`p-6 rounded-2xl border ${result ? 'bg-emerald-500/5 border-emerald-500/20' : 'bg-rose-500/5 border-rose-500/20'} animate-in fade-in slide-in-from-bottom-4 duration-500`}>
                            <div className="flex items-start gap-4">
                                <div className={`p-3 rounded-xl ${result ? 'bg-emerald-500/10 text-emerald-400' : 'bg-rose-500/10 text-rose-400'}`}>
                                    {result ? <CheckCircle2 className="w-6 h-6" /> : <AlertCircle className="w-6 h-6" />}
                                </div>
                                <div className="flex-1 min-w-0">
                                    <h4 className={`text-lg font-bold mb-1 ${result ? 'text-emerald-400' : 'text-rose-400'}`}>
                                        {result ? "Action Success" : "Scan Error"}
                                    </h4>
                                    <p className="text-zinc-400 text-sm leading-relaxed mb-4">
                                        {result ? result.message : error}
                                    </p>

                                    {result && result.metadata && (
                                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-2">
                                            <div className="bg-black/40 p-4 rounded-xl border border-white/5 space-y-2">
                                                <div className="flex items-center gap-2 text-zinc-500 text-[10px] uppercase font-bold tracking-widest">
                                                    <MapPin className="w-3 h-3" />
                                                    Location
                                                </div>
                                                <div className="text-sm font-bold text-zinc-200">
                                                    {result.metadata.roomCode} - {result.metadata.roomDesc}
                                                </div>
                                            </div>
                                            <div className="bg-black/40 p-4 rounded-xl border border-white/5 space-y-2">
                                                <div className="flex items-center gap-2 text-zinc-500 text-[10px] uppercase font-bold tracking-widest">
                                                    <Calendar className="w-3 h-3" />
                                                    Activity
                                                </div>
                                                <div className="text-sm font-bold text-zinc-200 truncate">
                                                    {result.metadata.activityTitle}
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Guidelines */}
                    <div className="bg-zinc-950/50 p-6 rounded-2xl border border-zinc-800/50 relative overflow-hidden group">
                        <div className="flex items-center gap-3 mb-4">
                            <Info className="w-4 h-4 text-zinc-500" />
                            <h3 className="text-xs font-black text-zinc-400 uppercase tracking-widest">Simulation Guide</h3>
                        </div>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-[11px] font-medium leading-relaxed text-zinc-500 italic">
                            <div className="flex gap-3">
                                <span className="text-orange-500/50 font-black tracking-tighter shrink-0">01.</span>
                                <p>Observe the client machine. Wait for a new QR code to be generated and catch the <span className="text-zinc-300">Token</span>.</p>
                            </div>
                            <div className="flex gap-3">
                                <span className="text-orange-500/50 font-black tracking-tighter shrink-0">02.</span>
                                <p>Enter your <span className="text-zinc-300">UserId</span> (admin or any student ID) and the captured token.</p>
                            </div>
                            <div className="flex gap-3">
                                <span className="text-orange-500/50 font-black tracking-tighter shrink-0">03.</span>
                                <p>The system will validate the token, link it to the machine's <span className="text-zinc-300">Room Metadata</span>, and record an audit log.</p>
                            </div>
                            <div className="flex gap-3">
                                <span className="text-orange-500/50 font-black tracking-tighter shrink-0">04.</span>
                                <p>Verify success in the <span className="text-zinc-300">Logs View</span> on the main dashboard.</p>
                            </div>
                        </div>
                    </div>
                </CardContent>
            </Card>
        </div>
    )
}
